### ISSUE TITLE
Links from popups with target=_blank do not open in new window

### ISSUE THREAD

**Issue by jdeck88** [birbjam/species-lookup#3]
Links from popups with target=_blank do not open in new window. instead they open in the current window... not sure why this is , but we want the links to open a new window!

**Comment by jdeck88** [comment]
just need to move the ending double quote on the href tag up a bit (line 28 in app.js) so it is: 

```htmlText = htmlText + '<li><a href="' + val.url+'" target=_blank>' + val.scientific_name +'</a></li>';```

**Comment by birbjam** [comment]
and done
